apiVersion: v1
kind: Service
metadata:
 name: myservice
 labels:
  app: myservicetesting
spec:
 selector:
  env: testing
 type: NodePort
 ports:
  - nodePort: 30000
    port: 81
    targetPort: 80